# Generated by Django 3.1.4 on 2020-12-29 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=50)),
                ('sender', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=200)),
                ('content', models.TextField()),
            ],
        ),
    ]
