# Generated by Django 3.1.4 on 2020-12-30 23:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20201229_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
