# Generated by Django 3.1.4 on 2020-12-31 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_photo_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='thumbnail',
        ),
    ]
