# Generated by Django 3.1.4 on 2020-12-31 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20201231_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='thumbnail',
            field=models.ImageField(blank=True, default='', upload_to='thumbnails'),
            preserve_default=False,
        ),
    ]
