# Generated by Django 3.1.4 on 2021-01-05 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20201231_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Make you Photo available/unavailable for purchase'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='pic',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Upload an image'),
        ),
    ]
