# Generated by Django 3.1.4 on 2020-12-29 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_auto_20201229_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='content',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='photo',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=10),
        ),
    ]
